Adds some mock methods to tests.
signalapp/Signal-iOS pull request #4638
Opened 2020-11-25 23:09 UTC by fumiakiy

### Contributor checklist

- [x] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [x] My commits are rebased on the latest master branch
- [x] My commits are in nice logical chunks
- [x] My contribution is fully baked and is ready to be merged as is
- [x] I have tested my contribution on these devices:
 * iPhone 11, iOS 13.5
 * Phone 12, iOS 14.2

- - - - - - - - - -

### Description

I found some tests need some mock methods to be implemented to be able to compile.

2021-01-12 18:54 UTC, mustafagunes requested changes

2021-01-12 18:54 UTC, mustafagunes commented on Signal/test/util/FTS/GRDBFullTextSearcherTest.swift
> +    }
```suggestion
    func conversationColorName(
        for address: SignalServiceAddress, 
        transaction: SDSAnyReadTransaction
    ) -> ConversationColorName {
        return ConversationColorName.indigo
    }
```

2021-01-12 18:54 UTC, mustafagunes commented on Signal/test/util/GroupAndContactStreamTest.swift
> +
```suggestion
    func conversationColorName(
        for address: SignalServiceAddress,
        transaction: SDSAnyReadTransaction
    ) -> ConversationColorName {
        return ConversationColorName.indigo
    }

```

2021-01-13 21:26 UTC, fumiakiy commented
Fixed in [111338b59d]. Closing.

2021-01-13 21:26 UTC, closed without merging