Minor improvements for German translation
signalapp/Signal-iOS pull request #4839
Opened 2021-01-26 15:44 UTC by thisdudeisvegan

### First time contributor checklist
- [X] I have read the [README](https://github.com/WhisperSystems/Signal-iOS/blob/master/README.md) and 
- [X] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist
- [X] I'm following the [code, UI and style conventions](https://github.com/WhisperSystems/Signal-iOS/blob/master/CONTRIBUTING.md#code-conventions)
- [X] My commits are rebased on the latest master branch
- [X] My commits are in nice logical chunks
- [X] My contribution is fully baked and is ready to be merged as is
- [X] I have tested my contribution on these devices:
 * iPhone 12 Pro Max, iOS 14.2

- - - - - - - - - -

### Description

2021-02-09 12:52 UTC, TristanBandat requested changes
Found a small typo at line 236. Please change, thanks!

2021-02-09 12:52 UTC, TristanBandat commented on Signal/translations/de.lproj/Localizable.strings
> +"ATTACHMENT_HINT" = "Medieninhalte zum versenden auswählen";
"Medieninhalte zum Versenden auswählen" would be correct. Words after 'zum' are starting almost always with a uppercase letter!

2021-02-15 09:14 UTC, ZER0-X commented
There is a special platform for translations, modification is not done directly to the code.

2021-02-18 12:16 UTC, Plarome commented
Translation is done here: https://www.transifex.com/signalapp/public/

2021-08-18 22:42 UTC, closed without merging